<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href="../normalize.css" rel="stylesheet" type="text/css">
        <link href="../Reset.css" rel="stylesheet" type="text/css">

        <link href="css/stylesheet.css" rel="stylesheet" type="text/css" >
        <title>Blog</title>
    

    </head>
<body>

