<?php if (isset($errorMsg)): ?>
<p>Erreur : <?= $errorMsg ?></p>
<?php endif ?>

<div id="login">
<form action="login.php" method="post">

    <label for="userName">Email</label>
    <input type="text" placeholder="Email or Username" name="userName">

    <label for="password">Password</label>
    <input type="text" placeholder="Password" name="password">

    <input type="submit" value="Sign in">
</form>

<p>Pas encore de compte ?<a href="register.php">Inscrivez-vous !</a></p>
</div>