<form action="post.php" method="post">

    <label for="title">Title</label><br/>
    <input type="text" id="title" name="title"><br/>

    <label for="tags">Tags</label><br/>
    <input type="text" id="tags" name="tags" ><br/>

    <label for="picture">Picture</label><br/>
    <input type="file" id="picture" value="Parcourir..."><br/>

    <label for="post">Post content</label><br/>
    <textarea name="content"></textarea><br/>

    <input type="submit" value="Submit" id="submit">
</form>