<?php if (isset($errorMsg)): ?>
    <p>Erreur : <?= $errorMsg ?></p>
<?php endif ?>

<form action="register.php" method="post">
    <label for="name">Name</label>
    <input type="text" placeholder="name" name="userName">

    <label for="email">Email</label>
    <input type="text" placeholder="Email" name="email">

    <label for="Password">Password</label>
    <input type="text" placeholder="Password" name="password">

    <input type="submit" value="Sign in">
</form>